version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'mysql'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - '0.0.0.0:8000:8000'
    restart: unless-stopped
    depends_on:
      - db

volumes:
  mysql-data:
    external: true
